/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogPagListResponseDataItemAttributesCreatedBy } from './blogPagListResponseDataItemAttributesCreatedBy';
import { LayoutPageInfoComponentCover } from './layoutPageInfoComponentCover';
import { LayoutPageInfoComponentCoverAttributesRelated } from './layoutPageInfoComponentCoverAttributesRelated';
import { LayoutPageInfoComponentSeo } from './layoutPageInfoComponentSeo';

export interface BlogPostsSelectionComponentFeaturedPostsAttributes { 
    content?: string;
    title?: string;
    slug?: string;
    cover?: LayoutPageInfoComponentCover;
    authors?: LayoutPageInfoComponentCoverAttributesRelated;
    tags?: LayoutPageInfoComponentCoverAttributesRelated;
    seo?: LayoutPageInfoComponentSeo;
    createdAt?: Date;
    updatedAt?: Date;
    publishedAt?: Date;
    createdBy?: BlogPagListResponseDataItemAttributesCreatedBy;
    updatedBy?: BlogPagListResponseDataItemAttributesCreatedBy;
}