/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogPagListResponseDataItemAttributesCreatedBy } from './blogPagListResponseDataItemAttributesCreatedBy';
import { CompanyInfoListResponseDataItemAttributesLogo } from './companyInfoListResponseDataItemAttributesLogo';
import { ConfigSocialLinkComponent } from './configSocialLinkComponent';
import { LayoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy } from './layoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy';

export interface CompanyInfoListResponseDataItemAttributes { 
    logo?: CompanyInfoListResponseDataItemAttributesLogo;
    socialLinks?: Array<ConfigSocialLinkComponent>;
    companyEmail?: string;
    companyName?: string;
    vat?: string;
    companyAddress?: string;
    createdAt?: Date;
    updatedAt?: Date;
    createdBy?: LayoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy;
    updatedBy?: BlogPagListResponseDataItemAttributesCreatedBy;
}