/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ConfigSocialLinkComponent { 
    id?: string;
    socialMedia?: ConfigSocialLinkComponent.SocialMediaEnum;
    link?: string;
}
export namespace ConfigSocialLinkComponent {
    export type SocialMediaEnum = 'github' | 'youtube' | 'twitter' | 'facebook' | 'whatsapp';
    export const SocialMediaEnum = {
        Github: 'github' as SocialMediaEnum,
        Youtube: 'youtube' as SocialMediaEnum,
        Twitter: 'twitter' as SocialMediaEnum,
        Facebook: 'facebook' as SocialMediaEnum,
        Whatsapp: 'whatsapp' as SocialMediaEnum
    };
}