/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogPagListResponseDataItemAttributesCreatedBy } from './blogPagListResponseDataItemAttributesCreatedBy';
import { LayoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy } from './layoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy';
import { LayoutPageInfoComponentCoverAttributesRelated } from './layoutPageInfoComponentCoverAttributesRelated';

export interface LayoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributes { 
    name?: string;
    alternativeText?: string;
    caption?: string;
    width?: number;
    height?: number;
    formats?: any;
    hash?: string;
    ext?: string;
    mime?: string;
    size?: number;
    url?: string;
    previewUrl?: string;
    provider?: string;
    providerMetadata?: any;
    related?: LayoutPageInfoComponentCoverAttributesRelated;
    folder?: BlogPagListResponseDataItemAttributesCreatedBy;
    folderPath?: string;
    createdAt?: Date;
    updatedAt?: Date;
    createdBy?: LayoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy;
    updatedBy?: BlogPagListResponseDataItemAttributesCreatedBy;
}