/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogPagListResponseDataItemAttributesCreatedBy } from './blogPagListResponseDataItemAttributesCreatedBy';
import { CompanyInfoListResponseDataItemAttributesLogo } from './companyInfoListResponseDataItemAttributesLogo';
import { LayoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy } from './layoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy';

export interface LayoutServicesPreviewComponentServicesAttributes { 
    name?: string;
    description?: string;
    slug?: string;
    cover?: CompanyInfoListResponseDataItemAttributesLogo;
    createdAt?: Date;
    updatedAt?: Date;
    publishedAt?: Date;
    createdBy?: LayoutPageInfoComponentCoverAttributesFolderDataAttributesFilesAttributesCreatedBy;
    updatedBy?: BlogPagListResponseDataItemAttributesCreatedBy;
}