/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SeoSeoinformationComponent } from './seoSeoinformationComponent';

export interface PostRequestData { 
    content: string;
    title: string;
    slug: string;
    cover?: Array<number | string>;
    authors?: Array<number | string>;
    tags?: Array<number | string>;
    seo?: SeoSeoinformationComponent;
}