/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogPagListResponseDataItemAttributesCreatedBy } from './blogPagListResponseDataItemAttributesCreatedBy';
import { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions';
import { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers } from './usersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers';

export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributes { 
    name?: string;
    description?: string;
    type?: string;
    permissions?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions;
    users?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers;
    createdAt?: Date;
    updatedAt?: Date;
    createdBy?: BlogPagListResponseDataItemAttributesCreatedBy;
    updatedBy?: BlogPagListResponseDataItemAttributesCreatedBy;
}